/**
 * BlockMarkets Cryptocurrency API
 * The BlockMarkets API provides real-time and historical market data on cryptocurrencies from the world's leading crypto exchanges. Sign up for a free, unlimited API key at [BlockMarkets Cryptocurrency API](https://www.blockmarkets.io/cryptocurrency-api).
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.blockmarkets) {
      root.blockmarkets = {};
    }
    root.blockmarkets.Empty = factory(root.blockmarkets.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Empty model module.
   * @module model/Empty
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Empty</code>.
   * @alias module:model/Empty
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Empty</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Empty} obj Optional instance to populate.
   * @return {module:model/Empty} The populated <code>Empty</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
    }
    return obj;
  }




  return exports;
}));


